### ISSUE TITLE
Conversion error with update of AWS package S3 API

### ISSUE THREAD

**Issue by AndrewBMartin** [amitmurthy/AWS.jl#29] opened 2015-06-04 15:34 UTC
I was getting this error when I installed julia 0.3.8 on Ubuntu Trusty:
```julia
ERROR: `convert` has no method matching convert(::Type{String}, ::Array{String,1})
 in convert at base.jl:13
 in do_request at /home/ubuntu/.julia/v0.3/AWS/src/S3.jl:571
 in get_object at /home/ubuntu/.julia/v0.3/AWS/src/S3.jl:392
```
The do_http method was returning an object where the http_headers dictionary had values of Array{String, 1} instead of Type{String} as the S3Response object expected.

I've fixed this temporarily in my codebase by checking to see if each header key has a value, and then if it does, assigning the first index of the array to the S3Response object.

For the version of AWS in the julia package repo, something might need to be changed to either have do_http return http_headers as a dictionary of Type{String} or update the S3Response type to have fields of Array{String, 1} instead of String.

**Comment by merl-dev** [comment] 2015-06-06 11:15
(I haven't made the code base changes to get around this)

Suddenly all of our S3 retrieval routines are broken, and this seems to have taken place right after you made some updates to the AWS.jl library 2 days ago.

We are heavily dependent on this library for our production systems, and all has come to a dead stop since.  Could you either revert or fix?  I'm gonna have about 100 hundred traders screaming at me if we don't get this online by tomorrow morning (we work sundays).
julia> ERROR: `convert` has no method matching convert(::Type{Int64}, ::Array{Int64,1})
        in convert at base.jl:13
        in do_request at /home/ubuntu/.julia/v0.3/AWS/src/S3.jl:571
        in get_object at /home/ubuntu/.julia/v0.3/AWS/src/S3.jl:392
        in get_s3 at /home/ubuntu/Merl/src/Merl_aws.jl:56

the last line here refers to the following call
resp = AWS.S3.get_object(env, bucket, src)
where env = your default AWSEnv method but with our ID and KEY and REGION: env=AWSEnv(;id=aws_id,key=aws_skey,ep=s3_region,timeout=60.0)
bucket is just a string with bucket name
and src is just the file name

**Comment by amitmurthy** [comment] 2015-06-06 11:58
The issue is actually with the latest HTTPClient commit.

https://github.com/JuliaWeb/HTTPClient.jl/commit/18a1cec7c934ab6d7d42916010ad0de31394f892 was changed a ways back to return an array of strings as part of the headers dict.

But HTTPClient in METADATA was changed 2 days back to refer to the latest HTTPClient commit.
 
The 2-day old AWS commit is dependent on Julia 0.4 and it seems like you are using Julia 0.3 and hence unlikely that you are using this.

What has happened is that you have an older AWS.jl but latest HTTPClient.

**Comment by amitmurthy** [comment] 2015-06-06 12:17
Can you guys go back to a commit of HTTPClient before https://github.com/JuliaWeb/HTTPClient.jl/commit/18a1cec7c934ab6d7d42916010ad0de31394f892 ?

**Comment by amitmurthy** [comment] 2015-06-06 12:30
I think the METADATA commit when merged should fix this issue.

**Comment by tkelman** [comment] 2015-06-06 12:39
https://github.com/JuliaLang/METADATA.jl/pull/2703 is a lower bound though, isn't the issue that more recent versions of HTTPClient had a breaking change but only bumped the patch version number when tagging that change?

(PS on production systems you should be very careful any time you do `Pkg.update()`, best to run a test suite in a staging area before deploying any update)

**Comment by amitmurthy** [comment] 2015-06-06 12:41
OK. Then I need to update it to using only version  0.1.4. I believe the syntax is

`HTTPClient  0.1.4  0.1.5-`  in the requires file?

**Comment by amitmurthy** [comment] 2015-06-06 12:42
Just re-read the doc. I believe it is `HTTPClient 0.1.4 0.1.5` .

**Comment by tkelman** [comment] 2015-06-06 12:43
I think so. Not very many packages have been applying upper bounds.

ref http://docs.julialang.org/en/latest/manual/packages/#man-package-requirements and http://docs.julialang.org/en/latest/manual/strings/?#version-number-literals

**Comment by amitmurthy** [comment] 2015-06-06 12:53
Have updated METADATA with the correct settings. Can you do a `Pkg.update()` and test it out?

**Comment by merl-dev** [comment] 2015-06-06 15:22
OK did a Pkg.update()... working fine now!  Thanks

**Closed** 2015-06-06 16:38 UTC

**Comment by somasdhavala** [comment] 2016-05-20 14:33
Guys I am having the same problem:
`resp=S3.list_all_buckets(env)` 
works OK but
resp = S3.get_bkt(env, "my_bucket")
fails
```
ERROR: MethodError: `convert` has no method matching convert(::Type{Union{LightXML.XMLElement,Void}}, ::ASCIIString)
This may have arisen from a call to the constructor Union{LightXML.XMLElement,Void}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, ::T)
 in do_request at /Users/soma/.julia/v0.4/AWS/src/S3.jl:640
 [inlined code] from /Users/soma/.julia/v0.4/AWS/src/S3.jl:47
 in __get_bkt#688__ at /Users/soma/.julia/v0.4/AWS/src/S3.jl:159
```
Am on
```
Version 0.4.5 (2016-03-18 00:58 UTC)
86_64-apple-darwin13.4.0]
```
I did 
`Pkg.update()`

**Comment by merl-dev** [comment] 2016-05-20 14:41
Haven't had any issues like this since,  however that error may happen when the "env" parameter is not set correctly...

**Comment by somasdhavala** [comment] 2016-05-20 14:43
I only supplied aws id and key. set time_out to 60 (default). The listing of buckets is shown correctly.
`env = AWSEnv(timeout=60.0,key="**",id="**")`

**Comment by s2maki** [comment] 2016-05-20 15:06
I think this can happen if the credentials you provided don't have access
to the bucket.  Try making the bucket publicly readable.

*Keith Mason*
Vice President | Application Platform and Quality Engineering

Conning | One Financial Plaza, Hartford, CT 06103, USA
*D* +1 860 299 2671   *F* +1 512 692 9134   *E* keith.mason@conning.com

<http://www.conning.com/>
<https://www.youtube.com/user/ConningCentennial>
<http://www.linkedin.com/company/conning>  <https://twitter.com/ConningNews>

On Fri, May 20, 2016 at 10:43 AM, somasdhavala <notifications@github.com>
wrote:

> I only supplied aws id and key. set time_out to 60 (default). The listing
> of buckets is shown correctly.
> env = AWSEnv(timeout=60.0,key="**",id="**")
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaParallel/AWS.jl/issues/29#issuecomment-220625256>
>

-- 


Please click here 
<http://www.e-disclaimer.com/conning/EE06B3FA5D199E20A3F7D0AE080A38FF.htm> for 
important information regarding this e-mail communication.

**Comment by merl-dev** [comment] 2016-05-20 15:07
well I just tested a fresh install of the AWS with a new set of credentials and it works fine, so I agree with @s2maki , it's likely an issue with your creds/env parameter

**Comment by s2maki** [comment] 2016-05-20 15:15
I am reading into the failed convert, and noting both the type to be
converted is ASCIIString and that the line of code throwing the exception
is in the case where the HTTP status is > 299.  The AWS library is
expecting XML data to have come back from the request, but the result is a
normal string.  In all likelihood, the string is an error message.  The
package should handle this situation better.

*Keith Mason*
Vice President | Application Platform and Quality Engineering

Conning | One Financial Plaza, Hartford, CT 06103, USA
*D* +1 860 299 2671   *F* +1 512 692 9134   *E* keith.mason@conning.com

<http://www.conning.com/>
<https://www.youtube.com/user/ConningCentennial>
<http://www.linkedin.com/company/conning>  <https://twitter.com/ConningNews>

On Fri, May 20, 2016 at 11:07 AM, Yaakov Borstein <notifications@github.com>
wrote:

> well I just tested a fresh install of the AWS with a new set of
> credentials and it works fine, so I agree with @s2maki
> <https://github.com/s2maki> , it's likely an issue with your creds/env
> parameter
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaParallel/AWS.jl/issues/29#issuecomment-220631909>
>

-- 


Please click here 
<http://www.e-disclaimer.com/conning/EE06B3FA5D199E20A3F7D0AE080A38FF.htm> for 
important information regarding this e-mail communication.

**Comment by somasdhavala** [comment] 2016-05-20 16:55
with the same credentials, I am able to list the buckets content using `s3cmd` utils

**Comment by samoconnor** [comment] 2016-05-21 00:31
Have you tried  https://github.com/samoconnor/AWSS3.jl

It has a [s3_list_objects](https://github.com/samoconnor/AWSS3.jl/blob/master/src/AWSS3.jl#L246) function

**Comment by samoconnor** [comment] 2016-05-21 00:37
@s2maki the AWACore.jl error parsing code tries fairly hard to ectract something useful from error messages regardless of content type: https://github.com/samoconnor/AWSCore.jl/blob/master/src/AWSException.jl#L22
You may find that borrowing that code for AWS.jl is useful.

**Comment by somasdhavala** [comment] 2016-05-21 02:45
thanks @samoconnor, AWSS3 was useful, I could read them now.

**Comment by merl-dev** [comment] 2016-05-21 14:49
No need to move outside the package (s3cmd or other options).  This works fine now.
